webtalk_init -webtalk_dir C:\\Users\\Student\\Documents\\GitHub\\CSM152B_S23\\final\\project_3a.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2023-06-02 12:50:32" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211888400_0_0_236" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "938ksqi5hcvndki2pr6vutrbfu" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_26" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.411 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1685735025739" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key Device -value "7a35t" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1685735025739"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1685735432331"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1685735432331"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1685735432331"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1685735432331"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1685735432331"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1685735432331"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1685735432331"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1685735432331"
webtalk_transmit -clientid 1549406550 -regid "211888400_0_0_236" -xml C:\\Users\\Student\\Documents\\GitHub\\CSM152B_S23\\final\\project_3a.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Student\\Documents\\GitHub\\CSM152B_S23\\final\\project_3a.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Student\\Documents\\GitHub\\CSM152B_S23\\final\\project_3a.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
